<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Promises</title>
</head>
<body>
    <script>
        // Promises represents data you might get in the future, for example a user's webcam.
        // Need to wait for something to happen first.

        function makePizza(toppings = []) {
            return new Promise(function(resolve, reject) {
                // check if someone put pineapple on, then reject
                if(toppings.includes('pineapple')) {
                    reject('Seriously? Get out');
                }

                const amountOfTimeToBake = 500 + (toppings.length * 200)

                // wait one second for pizza to cook
                setTimeout(function() {
                    // when you are ready, you can resolve this promise
                    resolve(`Here is your pizza 🍕 with the toppings ${toppings.join(' ')}`);
                }, amountOfTimeToBake);

                // if something went wrong, we can reject it

            });
        }

        // This is sequential, they happen one at a time
        // When an error is encountered in a promise chain, the rest of the chain stops running. If you need it to keep running, you must use some static methods such as all
        makePizza(['pepperoni']).then(function (pizza) {
            console.log(pizza);
            return makePizza(['ham', 'cheese']);
        }).then(function(pizza) {
            console.log(pizza);
            return makePizza(['hot peppers', 'onion', 'feta']);
        }).then(function(pizza) {
            console.log(pizza);
            return makePizza(['pineapple']);
        }).then(function(pizza) {
            console.log(pizza);
            return makePizza(['one', 'two', 'three', 'four', 'five', 'one', 'two', 'three', 'four', 'five']);
        }).then(pizza => {
            console.log('All done! here is your last pizza');
            console.log(pizza);
        })
        .catch(handleError)

        // // Run them concurrently
        // const pizzaPromise1 = makePizza(['hot peppers', 'onion', 'feta']);
        // const pizzaPromise2 = makePizza(['one', 'two', 'three', 'four', 'five', 'one', 'two', 'three', 'four', 'five']);
        // const pizzaPromise3 = makePizza(['ham', 'cheese']);

        // // Create mega promise that runs when all three pizzas are done
        // // Promise.all is a static method that takes in promises
        // const dinnerPromise = Promise.all([pizzaPromise1, pizzaPromise2, pizzaPromise3]);

        // dinnerPromise.then(function([hottie, garbagePail, hamAndCheese]) {

        //     console.log(hottie, garbagePail, hamAndCheese);
        // });

        // const firstPizzaPromise = Promise.race([pizzaPromise1, pizzaPromise2, pizzaPromise3]);

        // firstPizzaPromise.then(pizza => {
        //     console.log('You must be hungry! Here is the first one ready: ')
        //     console.log(pizza);
        // });

        // pepperoniPromise.then(function(pizza) {
        //     console.log('Ahh, got it!');
        //     console.log(pizza);
        // });

        function handleError(err) {
            console.log('Oh nooo!');
            console.log(err);
        }

        // The .then only runs when function runs successfully
        // The .catch will only run when function doesn't go successfully
        // With Promise-based functions, you usually chain a .then and .catch
        makePizza(['cheese', 'pineapple'])
            .then(pizza => {
            console.log(pizza);
        }).catch(handleError)

        const p1 = makePizza(['pep']);
        const p2 = makePizza(['pineapple']);

        // Promise.allSettled() tells you when they're all done regardless of whether they error out or not
        const dinnerPromise2 = Promise.allSettled([p1, p2]);

        dinnerPromise2.then(results => {
            console.log(results);
        })
    </script>

</body>
</html>